<?php

namespace AppBundle\Repository;

/**
 * AttrValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttrValueRepository extends \Doctrine\ORM\EntityRepository
{
}
