<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllByName($name)
    {
        return  $this->getEntityManager()->createQuery('SELECT * FROM AppBundle\Repository\CategoryRepository WHERE p.name LIKE '.$name);
    }
}
