<?php

namespace AppBundle\Repository;

/**
 * ChangeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeLogRepository extends \Doctrine\ORM\EntityRepository
{
}
