getAllCategory:
    path:      /category
    methods: [GET]
    defaults:  { _controller: AppBundle:Catalog:getAllCategory }
getCategory:
    path:      /category/{id}
    methods: [GET]
    defaults:  { _controller: AppBundle:Catalog:getCategory }
postCategory:
    path:      /category
    methods: [POST]
    defaults:  { _controller: AppBundle:Catalog:postCategory }
getAllItem:
    path: /items
    methods: [GET]
    defaults: { _controller: AppBundle:Catalog:getAllItem}
getItem:
    path: /items/{id}
    methods: [GET]
    defaults: { _controller: AppBundle:Catalog:getItem}
postItem:
    path: /items
    methods: [POST]
    defaults: { _controller: AppBundle:Catalog:postItem}