AppBundle\Entity\Item:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
            groups: [getItem]
        name:
            access_type: public_method
            expose: true
            type: string
            groups: [getItem, setItem]
        price:
            access_type: public_method
            expose: true
            type: integer
            groups: [getItem, setItem]
        color:
            access_type: public_method
            expose: true
            type: string
            groups: [getItem, setItem]
        size:
            access_type: public_method
            expose: true
            type: integer
            groups: [getItem, setItem]
        weight:
            access_type: public_method
            expose: true
            type: integer
            groups: [getItem, setItem]
        categories:
            type: ArrayCollection<AppBundle\Entity\Category>
            expose: true
            access_type: public_method
            groups: [getItem, setItem]