AppBundle\Entity\Item:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
            groups: [getItem]
        name:
            access_type: public_method
            expose: true
            type: string
            groups: [getItem, setItem]
        categories:
            type: ArrayCollection<AppBundle\Entity\Category>
            expose: true
            access_type: public_method
            groups: [getItem, setItem]
        attributes:
            type: ArrayCollection<AppBundle\Entity\AttrValue>
            expose: true
            groups: [getItem, setItem]