AppBundle\Entity\Attribute:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
            groups: [get]
        alias:
            access_type: public_method
            expose: true
            type: string
            groups: [get, set]
        name:
            access_type: public_method
            expose: true
            type: string
            groups: [get, set]
        attrValues:
            access_type: public_method
            expose: true
            #type: string
            groups: [get, set]