AppBundle\Entity\ChangeLog:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
        date:
            access_type: public_method
            expose: true
            type: datetime
        user:
            access_type: public_method
            expose: true
            type: string
        entityName:
            access_type: public_method
            expose: true
            type: string
        entityId:
            access_type: public_method
            type: int
            expose: true
        action:
            access_type: public_method
            type: string
            expose: true
        changeSet:
            access_type: public_method
            type: array
            expose: true
        description:
            access_type: public_method
            type: string
            expose: true