AppBundle\Entity\AuthCode:
    type: entity
    table: oauth2_auth_codes
    repositoryClass: AppBundle\Repository\AuthCodeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        client:
            targetEntity: AppBundle\Entity\Client
            joinColumn:
                nullable: false
        user:
            targetEntity: AppBundle\Entity\User

    lifecycleCallbacks: {  }
