AppBundle\Entity\Category:
    type: entity
    table: category
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
              strategy: AUTO
    fields:
        name:
            type: string
            lenght: 255
        createdAt:
            type: datetime
            nullable: true
        updatedAt:
            type: datetime
            nullable: true

    oneToMany:
        children:
            targetEntity: AppBundle\Entity\Category
            mappedBy: parent
            #orderBy:
                #name: ASC
    manyToOne:
        parent:
            targetEntity: AppBundle\Entity\Category
            inversedBy: children
            joinColumn:
                name: parentId
                referencedColumn: id
    manyToMany:
        items:
            targetEntity: AppBundle\Entity\Item
            mappedBy: categories
            cascade: ['persist','merge']
    lifecycleCallbacks:
        prePersist: [setCreatedAt]
        preUpdate: [setUpdatedAt]