AppBundle\Entity\Category:
  type: entity
  lifecycleCallbacks:
        prePersist: [setCreatedAt]
        preUpdate: [setUpdatedAt]
  oneToMany:
        children:
            targetEntity: AppBundle\Entity\Category
            mappedBy: parent
            #orderBy:
                #name: ASC
  manyToOne:
        parent:
            targetEntity: AppBundle\Entity\Category
            inversedBy: children
            joinColumn:
                name: parentId
                referencedColumn: id
  manyToMany:
        items:
            targetEntity: AppBundle\Entity\Item
            mappedBy: categories
            cascade: ['persist','merge']
  table: category
  repositoryClass: AppBundle\Repository\CategoryRepository
  id:
      id:
          column: id
          type: integer
          id: true
          generator:
              strategy: AUTO
  fields:
      name:
          type: string
          lenght: 255
      createdAt:
          type: datetime
          nullable: true
      updatedAt:
          type: datetime
          nullable: true


