AppBundle\Entity\Category:
  type: entity
  manyToOne:
      parent:
          targetEntity: AppBundle\Entity\Category
          inversedBy: name
          joinColumn:
              name: parentId
              referencedColumn: id
  table: category
  repositoryClass: AppBundle\Repository\CategoryRepository
  id:
      id:
          column: id
          type: integer
          id: true
          generator:
              strategy: AUTO
  fields:
      name:
          type: string
          lenght: 255


