AppBundle\Entity\ChangeLog:
    type: entity
    table: change_log
    repositoryClass: AppBundle\Repository\ChangeLogRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: string
        user:
            type: string
            length: 255
        entityName:
            type: string
            length: 255
        entityId:
            type: integer
        action:
            type: string
            length: 255
        fieldName:
            type: string
        oldValue:
            type: string
            nullable: true
        newValue:
            type: string
            nullable: true

    lifecycleCallbacks: {  }
